### ISSUE TITLE
Errors on both enum_select and multi_select

### ISSUE THREAD

**Issue by ZASMan** [piotrmurach/tty-prompt#158] opened 2021-02-16 14:13 UTC
### Are you in the right place?
* For issues or feature requests file a GitHub issue in this repository
* For general questions or discussion post in [Gitter](https://gitter.im/piotrmurach/tty)

### Describe the problem
I have a simple ruby script where I'm trying to implement this prompt on a particularly long list, and I can't get it to work. It just takes forever to load and I get these errors when I finally do ctrl + c
### Steps to reproduce the problem
```
require 'git'
require "tty-prompt"

repo_name_list = ['repo_name_1', 'repo_name_2']
prompt = TTY::Prompt.new
prompt.multi_select("Which repos would you like to clone locally?", repo_name_list)
# NoMethodError: undefined method `disabled?' for nil:NilClass
prompt.enum_select("Which repos would you like to clone locally?", repo_name_list)
# NoMethodError: undefined method `disabled?' for nil:NilClass
```

### Actual behaviour
What happened? This could be a description, log output, error raised etc...

### Expected behaviour
What did you expect to happen?

### Describe your environment

* OS version: Mac OS High Sierra Version 13.0.6
* Ruby version: 2.5.1
* TTY::Prompt version: tty-prompt (0.23.0)

**Comment by piotrmurach** [comment] 2021-02-16 19:02
Hi Zane 👋 

Thank you for checking out `tty-prompt`.

I run  your example, here below for reference in the console:

```ruby
require 'git'
require "tty-prompt"

repo_name_list = ['repo_name_1', 'repo_name_2']
prompt = TTY::Prompt.new
prompt.multi_select("Which repos would you like to clone locally?", repo_name_list)
```

And the `multi_select` prompt renders as expected:

![zasman-bug](https://user-images.githubusercontent.com/444312/108108126-7a09db80-7090-11eb-80d8-ee09d2c782ea.png)

And allows for selection:

![zasman-bug-2](https://user-images.githubusercontent.com/444312/108108215-9c9bf480-7090-11eb-90d9-0fd4dea8e024.png)

Therefore, I cannot reproduce any errors that you're seeing. Would you be able to provide a minimal example of something that fails? I will need a precise example with inputs that break a prompt.

**Comment by piotrmurach** [comment] 2021-02-18 19:07
I'm closing this ticket due to lack of reproducible error example. Please free to reopen if you still experience any errors and can provide steps to reproduce.

**Closed by piotrmurach** 2021-02-18 19:07 UTC
